// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicioSistemaWebProxyGdebaDvba.Infrastructure.Persistence;

#nullable disable

namespace ServicioSistemaWebProxyGdebaDvba.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProxyGdebaDbContext))]
    [Migration("20260622155012_AgregaFuncionEstadisticaExpedientesPorTrata")]
    partial class AgregaFuncionEstadisticaExpedientesPorTrata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Application.Estadisticas.Models.EstadisticaExpedientesPorTrataReadModel", b =>
                {
                    b.Property<string>("CodigoTrata")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DescripcionTrata")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TotalExpedientes")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.AplicacionConsumidora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("AplicacionesConsumidoras", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ArchivoAdjuntoExpediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaPrimeraDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaUltimaDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FuenteDeteccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId", "NombreArchivo")
                        .IsUnique();

                    b.ToTable("ArchivosAdjuntosExpediente", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoArchivoLocal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExtensionArchivo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("FechaDescarga")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaVerificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HashContenido")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("LongitudBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("RutaRelativa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StorageProvider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId")
                        .IsUnique();

                    b.HasIndex("StorageKey");

                    b.ToTable("DocumentoArchivosLocales", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoCacheControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaCompleto")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaPrimeraDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaActualizacionLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaConsultaGdeba")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaVencimiento")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FuenteUltimaRespuesta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TieneDatosParciales")
                        .HasColumnType("bit");

                    b.Property<string>("UltimoErrorConsulta")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId")
                        .IsUnique();

                    b.HasIndex("FechaVencimiento");

                    b.ToTable("DocumentoCacheControls", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoGdeba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActuacionAnio")
                        .HasColumnType("int");

                    b.Property<long>("ActuacionNumero")
                        .HasColumnType("bigint");

                    b.Property<string>("ActuacionReparticion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActuacionSistema")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ActuacionTipoCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("EspecialAnio")
                        .HasColumnType("int");

                    b.Property<long?>("EspecialNumero")
                        .HasColumnType("bigint");

                    b.Property<string>("EspecialReparticion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EspecialSistema")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EspecialTipoCodigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimoEnriquecimiento")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ListaFirmantes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("MetadataCompleta")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroActuacionCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroEspecialCompleto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("PuedeVerDocumento")
                        .HasColumnType("bit");

                    b.Property<string>("Referencia")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TipoDocumentoCodigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoDocumentoDescripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("TipoDocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoDocumentoNombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UrlArchivo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroActuacionCompleto")
                        .IsUnique();

                    b.HasIndex("NumeroEspecialCompleto")
                        .IsUnique()
                        .HasFilter("[NumeroEspecialCompleto] IS NOT NULL");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("TipoDocumentoCodigo", "ActuacionReparticion");

                    b.HasIndex("ActuacionTipoCodigo", "ActuacionAnio", "ActuacionNumero", "ActuacionSistema", "ActuacionReparticion")
                        .IsUnique();

                    b.ToTable("DocumentosGdeba", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescripcionTramite")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EstadoActual")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FechaCaratulacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GdebaAnio")
                        .HasColumnType("int");

                    b.Property<long>("GdebaNumero")
                        .HasColumnType("bigint");

                    b.Property<string>("GdebaNumeroCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GdebaReparticion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GdebaSistema")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GdebaTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReparticionActual")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SectorDestino")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SistemaOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TrataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioCaratulador")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioDestino")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("GdebaNumeroCompleto")
                        .IsUnique();

                    b.HasIndex("TrataId");

                    b.HasIndex("GdebaAnio", "GdebaReparticion");

                    b.HasIndex("GdebaTipo", "GdebaAnio", "GdebaNumero", "GdebaSistema", "GdebaReparticion")
                        .IsUnique();

                    b.ToTable("Expedientes", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ExpedienteCacheControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaCompleto")
                        .HasColumnType("bit");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaPrimeraDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaActualizacionLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaConsultaGdeba")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaVencimiento")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FuenteUltimaRespuesta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TieneDatosParciales")
                        .HasColumnType("bit");

                    b.Property<string>("UltimoErrorConsulta")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId")
                        .IsUnique();

                    b.HasIndex("FechaVencimiento");

                    b.ToTable("ExpedienteCacheControls", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ExpedienteDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaPrimeraDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaUltimaDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaVinculacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FuenteDeteccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OrdenRespuesta")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAsociacion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioGenerador")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("ExpedienteId", "DocumentoId")
                        .IsUnique();

                    b.ToTable("ExpedienteDocumentos", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ExpedienteRelacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoTrataRelacionado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DescripcionTrataRelacionado")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("EsCabecera")
                        .HasColumnType("bit");

                    b.Property<Guid>("ExpedienteOrigenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExpedienteRelacionadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaPrimeraDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaRelacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaUltimaDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FuenteDeteccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroExpedienteRelacionado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoRelacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioRelacion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteRelacionadoId");

                    b.HasIndex("ExpedienteOrigenId", "TipoRelacion", "NumeroExpedienteRelacionado")
                        .IsUnique();

                    b.ToTable("ExpedienteRelaciones", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.HistorialDocumentoGdeba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Actividad")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("FechaFin")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaInicio")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("IdGdeba")
                        .HasColumnType("bigint");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("WorkflowOrigen")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId", "FechaInicio");

                    b.HasIndex("DocumentoId", "IdGdeba")
                        .IsUnique();

                    b.ToTable("HistorialDocumentosGdeba", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.HistorialExpedienteCacheControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaCompleto")
                        .HasColumnType("bit");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaPrimeraDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaActualizacionLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaConsultaGdeba")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaVencimiento")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FuenteUltimaRespuesta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TieneDatosParciales")
                        .HasColumnType("bit");

                    b.Property<string>("UltimoErrorConsulta")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("UltimoMovimientoDetectadoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId")
                        .IsUnique();

                    b.HasIndex("FechaVencimiento");

                    b.HasIndex("UltimoMovimientoDetectadoId");

                    b.ToTable("HistorialExpedienteCacheControls", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.InvocacionGdeba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("DuracionMilisegundos")
                        .HasColumnType("bigint");

                    b.Property<int?>("EstadoHttp")
                        .HasColumnType("int");

                    b.Property<bool>("Exitosa")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NumeroIntento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("OperacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("NoDeterminado");

                    b.Property<bool>("ServidorRespondio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("OperacionId");

                    b.HasIndex("SolicitudId", "NumeroIntento");

                    b.HasIndex("Ambiente", "Fecha", "OperacionId", "Origen");

                    b.ToTable("InvocacionesGdeba", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.MovimientoExpediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsUltimoConocido")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoDestino")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EstadoOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("FechaOperacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Motivo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("ReparticionDestino")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReparticionOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioDestino")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioOrigen")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId", "EsUltimoConocido");

                    b.HasIndex("ExpedienteId", "Orden");

                    b.ToTable("MovimientosExpediente", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.OperacionGdeba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int?>("LimiteDiario")
                        .HasColumnType("int");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("UmbralAdvertenciaPorcentaje")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(80m);

                    b.Property<decimal>("UmbralCriticoPorcentaje")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(90m);

                    b.HasKey("Id");

                    b.HasIndex("Servicio", "Metodo")
                        .IsUnique();

                    b.ToTable("OperacionesGdeba", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("AplicacionConsumidoraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Fuente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OperacionGdeba")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OperacionSolicitada")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Recurso")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("AplicacionConsumidoraId", "OperacionSolicitada", "Fecha");

                    b.ToTable("RegistrosAuditoria", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TipoDocumentoGdeba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoTipoDocumentoGdeba")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("EsAutomatica")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsComunicable")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsConfidencial")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsEmbebido")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsEspecial")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsFirmaConjunta")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsFirmaExterna")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsManual")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsNotificable")
                        .HasColumnType("bit");

                    b.Property<bool>("EsResolucion")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Familia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("TieneTemplate")
                        .HasColumnType("bit");

                    b.Property<bool?>("TieneToken")
                        .HasColumnType("bit");

                    b.Property<string>("TipoProduccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CodigoTipoDocumentoGdeba");

                    b.HasIndex("EsResolucion", "Activo");

                    b.HasIndex("Familia", "Activo");

                    b.ToTable("TiposDocumentoGdeba", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataCacheControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaCompleta")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaPrimeraDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaActualizacionLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaConsultaGdeba")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaVencimiento")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FuenteUltimaRespuesta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TrataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UltimoErrorConsulta")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("FechaVencimiento");

                    b.HasIndex("TrataId")
                        .IsUnique();

                    b.ToTable("TrataCacheControls", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataGdeba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcronimoGedo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("EsAutomatica")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsTrataManual")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdTrataGdeba")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoReservaDescripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoReservaDescripcionTipoReserva")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoReservaId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TratasGdeba", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ArchivoAdjuntoExpediente", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", "Expediente")
                        .WithMany("ArchivosAdjuntos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoArchivoLocal", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoGdeba", "Documento")
                        .WithOne("ArchivoLocal")
                        .HasForeignKey("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoArchivoLocal", "DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoCacheControl", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoGdeba", "Documento")
                        .WithOne("CacheControl")
                        .HasForeignKey("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoCacheControl", "DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoGdeba", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TipoDocumentoGdeba", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataGdeba", "Trata")
                        .WithMany("Expedientes")
                        .HasForeignKey("TrataId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Trata");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ExpedienteCacheControl", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", "Expediente")
                        .WithOne("CacheControl")
                        .HasForeignKey("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ExpedienteCacheControl", "ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ExpedienteDocumento", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoGdeba", "Documento")
                        .WithMany("Expedientes")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", "Expediente")
                        .WithMany("Documentos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ExpedienteRelacion", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", "ExpedienteOrigen")
                        .WithMany("Relaciones")
                        .HasForeignKey("ExpedienteOrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", "ExpedienteRelacionado")
                        .WithMany()
                        .HasForeignKey("ExpedienteRelacionadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExpedienteOrigen");

                    b.Navigation("ExpedienteRelacionado");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.HistorialDocumentoGdeba", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoGdeba", "Documento")
                        .WithMany("Historial")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.HistorialExpedienteCacheControl", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", "Expediente")
                        .WithOne("HistorialCacheControl")
                        .HasForeignKey("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.HistorialExpedienteCacheControl", "ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.MovimientoExpediente", "UltimoMovimientoDetectado")
                        .WithMany()
                        .HasForeignKey("UltimoMovimientoDetectadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Expediente");

                    b.Navigation("UltimoMovimientoDetectado");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.InvocacionGdeba", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.OperacionGdeba", "Operacion")
                        .WithMany("Invocaciones")
                        .HasForeignKey("OperacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operacion");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.MovimientoExpediente", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", "Expediente")
                        .WithMany("Movimientos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.RegistroAuditoria", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.AplicacionConsumidora", "AplicacionConsumidora")
                        .WithMany("RegistrosAuditoria")
                        .HasForeignKey("AplicacionConsumidoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AplicacionConsumidora");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataCacheControl", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataGdeba", "Trata")
                        .WithOne("CacheControl")
                        .HasForeignKey("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataCacheControl", "TrataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trata");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.AplicacionConsumidora", b =>
                {
                    b.Navigation("RegistrosAuditoria");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoGdeba", b =>
                {
                    b.Navigation("ArchivoLocal");

                    b.Navigation("CacheControl");

                    b.Navigation("Expedientes");

                    b.Navigation("Historial");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", b =>
                {
                    b.Navigation("ArchivosAdjuntos");

                    b.Navigation("CacheControl");

                    b.Navigation("Documentos");

                    b.Navigation("HistorialCacheControl");

                    b.Navigation("Movimientos");

                    b.Navigation("Relaciones");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.OperacionGdeba", b =>
                {
                    b.Navigation("Invocaciones");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataGdeba", b =>
                {
                    b.Navigation("CacheControl");

                    b.Navigation("Expedientes");
                });
#pragma warning restore 612, 618
        }
    }
}
