// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicioSistemaWebProxyGdebaDvba.Infrastructure.Persistence;

#nullable disable

namespace ServicioSistemaWebProxyGdebaDvba.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProxyGdebaDbContext))]
    [Migration("20260811200055_AgregaResultadosEjecucionWorkerDescubrimiento")]
    partial class AgregaResultadosEjecucionWorkerDescubrimiento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Application.Estadisticas.Models.EstadisticaExpedientesPorTrataReadModel", b =>
                {
                    b.Property<string>("CodigoTrata")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DescripcionTrata")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalExpedientes")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.AplicacionConsumidora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Seguridad_AplicacionesConsumidoras", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ArchivoAdjuntoExpediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaPrimeraDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaUltimaDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FuenteDeteccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId", "NombreArchivo")
                        .IsUnique();

                    b.ToTable("ArchivosAdjuntosExpediente", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Configuracion.ConfiguracionDescubrimientoEstadoExpediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstadoExpedienteGdebaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoExpedienteGdebaId")
                        .IsUnique();

                    b.HasIndex("Habilitado", "Prioridad");

                    b.ToTable("Configuracion_EstadosDescubrimientoExpediente", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Configuracion.ConfiguracionDescubrimientoTemaExpediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<Guid>("TemaExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TemaExpedienteId")
                        .IsUnique();

                    b.HasIndex("Habilitado", "Prioridad");

                    b.ToTable("Configuracion_TemasDescubrimientoExpediente", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Configuracion.ConfiguracionDescubrimientoTrataExpediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoTrata")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Habilitada")
                        .HasColumnType("bit");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoTrata")
                        .IsUnique();

                    b.HasIndex("Habilitada", "Prioridad");

                    b.ToTable("Configuracion_TratasDescubrimientoExpediente", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Configuracion.ConfiguracionEnriquecimientoMetadataDocumentoTemaExpediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<Guid>("TemaExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TemaExpedienteId")
                        .IsUnique();

                    b.HasIndex("Habilitado", "Prioridad");

                    b.ToTable("Configuracion_TemasEnriquecimientoMetadataDocumento", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Configuracion.ProcesoDescubrimientoTrataEstadoExpediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoTrata")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ConsultasSinResultadosConsecutivas")
                        .HasColumnType("int");

                    b.Property<Guid>("EstadoExpedienteGdebaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("FechaUltimaConsulta")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimoResultadoHabilitado")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("OmitirHasta")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OmitirHasta");

                    b.HasIndex("CodigoTrata", "EstadoExpedienteGdebaId")
                        .IsUnique();

                    b.ToTable("WorkerDescubrimiento_ExpedientesSegunTratasEstados", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoArchivoLocal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExtensionArchivo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("FechaDescarga")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaVerificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HashContenido")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("LongitudBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("RutaRelativa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StorageProvider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId")
                        .IsUnique();

                    b.HasIndex("StorageKey");

                    b.ToTable("DocumentoArchivosLocales", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoCacheControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaCompleto")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaPrimeraDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaActualizacionLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaConsultaGdeba")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaVencimiento")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FuenteUltimaRespuesta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UltimoErrorConsulta")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId")
                        .IsUnique();

                    b.HasIndex("FechaVencimiento");

                    b.ToTable("Cache_DocumentoControl", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoGdeba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActuacionAnio")
                        .HasColumnType("int");

                    b.Property<long>("ActuacionNumero")
                        .HasColumnType("bigint");

                    b.Property<string>("ActuacionReparticion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActuacionSistema")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ActuacionTipoCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("EspecialAnio")
                        .HasColumnType("int");

                    b.Property<long?>("EspecialNumero")
                        .HasColumnType("bigint");

                    b.Property<string>("EspecialReparticion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EspecialSistema")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EspecialTipoCodigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimoEnriquecimiento")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ListaFirmantes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("MetadataCompleta")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroActuacionCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroEspecialCompleto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("PuedeVerDocumento")
                        .HasColumnType("bit");

                    b.Property<string>("Referencia")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TipoDocumentoCodigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoDocumentoDescripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("TipoDocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoDocumentoNombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UrlArchivo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroActuacionCompleto")
                        .IsUnique();

                    b.HasIndex("NumeroEspecialCompleto")
                        .IsUnique()
                        .HasFilter("[NumeroEspecialCompleto] IS NOT NULL");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("TipoDocumentoCodigo", "ActuacionReparticion");

                    b.HasIndex("ActuacionTipoCodigo", "ActuacionAnio", "ActuacionNumero", "ActuacionSistema", "ActuacionReparticion")
                        .IsUnique();

                    b.ToTable("DocumentosGdeba", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.EstadoExpedienteGdeba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreGdeba")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NombreGdeba")
                        .IsUnique();

                    b.ToTable("EstadosExpedienteGdeba", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            NombreGdeba = "Iniciación"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            NombreGdeba = "Tramitación"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            NombreGdeba = "Comunicación"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            NombreGdeba = "Guarda Temporal"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            NombreGdeba = "Ejecución"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            NombreGdeba = "Pendiente Iniciación"
                        });
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescripcionTramite")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EstadoActual")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FechaCaratulacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GdebaAnio")
                        .HasColumnType("int");

                    b.Property<long>("GdebaNumero")
                        .HasColumnType("bigint");

                    b.Property<string>("GdebaNumeroCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GdebaReparticion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GdebaSistema")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GdebaTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReparticionActual")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SectorDestino")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SistemaOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TrataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioCaratulador")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioDestino")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("GdebaNumeroCompleto")
                        .IsUnique();

                    b.HasIndex("TrataId");

                    b.HasIndex("GdebaAnio", "GdebaReparticion");

                    b.HasIndex("GdebaTipo", "GdebaAnio", "GdebaNumero", "GdebaSistema", "GdebaReparticion")
                        .IsUnique();

                    b.ToTable("Expedientes", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ExpedienteCacheControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaCompleto")
                        .HasColumnType("bit");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaPrimeraDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaActualizacionLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaConsultaGdeba")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaVencimiento")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FuenteUltimaRespuesta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UltimoErrorConsulta")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId")
                        .IsUnique();

                    b.HasIndex("FechaVencimiento");

                    b.ToTable("Cache_ExpedienteControl", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ExpedienteDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaPrimeraDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaUltimaDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaVinculacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FuenteDeteccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OrdenRespuesta")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAsociacion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioGenerador")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("ExpedienteId", "DocumentoId")
                        .IsUnique();

                    b.ToTable("ExpedienteDocumentos", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ExpedienteRelacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoTrataRelacionado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DescripcionTrataRelacionado")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("EsCabecera")
                        .HasColumnType("bit");

                    b.Property<Guid>("ExpedienteOrigenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExpedienteRelacionadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaPrimeraDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaRelacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaUltimaDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FuenteDeteccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroExpedienteRelacionado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoRelacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioRelacion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteRelacionadoId");

                    b.HasIndex("ExpedienteOrigenId", "TipoRelacion", "NumeroExpedienteRelacionado")
                        .IsUnique();

                    b.ToTable("ExpedienteRelaciones", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.HistorialDocumentoGdeba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Actividad")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("FechaFin")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaInicio")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("IdGdeba")
                        .HasColumnType("bigint");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("WorkflowOrigen")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId", "FechaInicio");

                    b.HasIndex("DocumentoId", "IdGdeba")
                        .IsUnique();

                    b.ToTable("HistorialDocumentosGdeba", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.HistorialExpedienteCacheControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaCompleto")
                        .HasColumnType("bit");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaPrimeraDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaActualizacionLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaConsultaGdeba")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaVencimiento")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FuenteUltimaRespuesta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UltimoErrorConsulta")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("UltimoMovimientoDetectadoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId")
                        .IsUnique();

                    b.HasIndex("FechaVencimiento");

                    b.HasIndex("UltimoMovimientoDetectadoId");

                    b.ToTable("Cache_HistorialExpedienteControl", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.InvocacionGdeba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("DuracionMilisegundos")
                        .HasColumnType("bigint");

                    b.Property<int?>("EstadoHttp")
                        .HasColumnType("int");

                    b.Property<bool>("Exitosa")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NumeroIntento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("OperacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("NoDeterminado");

                    b.Property<bool>("ServidorRespondio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("OperacionId");

                    b.HasIndex("SolicitudId", "NumeroIntento");

                    b.HasIndex("Ambiente", "Fecha", "OperacionId", "Origen");

                    b.ToTable("IntegracionGdeba_Invocaciones", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.MovimientoExpediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsUltimoConocido")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoDestino")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EstadoOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("FechaOperacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Motivo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("ReparticionDestino")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReparticionOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioDestino")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioOrigen")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId", "EsUltimoConocido");

                    b.HasIndex("ExpedienteId", "Orden");

                    b.ToTable("MovimientosExpediente", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.OperacionGdeba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int?>("LimiteDiario")
                        .HasColumnType("int");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("UmbralAdvertenciaPorcentaje")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(80m);

                    b.Property<decimal>("UmbralCriticoPorcentaje")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(90m);

                    b.HasKey("Id");

                    b.HasIndex("Servicio", "Metodo")
                        .IsUnique();

                    b.ToTable("IntegracionGdeba_Operaciones", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("AplicacionConsumidoraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Fuente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OperacionGdeba")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OperacionSolicitada")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Recurso")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("AplicacionConsumidoraId", "OperacionSolicitada", "Fecha");

                    b.ToTable("Auditoria_Registros", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TemaExpediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TemasExpediente", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TemaExpedienteTrata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemaExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrataHabilitadaVialidadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TrataHabilitadaVialidadId");

                    b.HasIndex("TemaExpedienteId", "TrataHabilitadaVialidadId")
                        .IsUnique();

                    b.ToTable("TemaExpedienteTratas", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TipoDocumentoGdeba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoTipoDocumentoGdeba")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("EsAutomatica")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsComunicable")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsConfidencial")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsEmbebido")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsEspecial")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsFirmaConjunta")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsFirmaExterna")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsManual")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsNotificable")
                        .HasColumnType("bit");

                    b.Property<bool>("EsResolucion")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Familia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("TieneTemplate")
                        .HasColumnType("bit");

                    b.Property<bool?>("TieneToken")
                        .HasColumnType("bit");

                    b.Property<string>("TipoProduccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CodigoTipoDocumentoGdeba");

                    b.HasIndex("EsResolucion", "Activo");

                    b.HasIndex("Familia", "Activo");

                    b.ToTable("TiposDocumentoGdeba", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataCacheControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaCompleta")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaPrimeraDeteccion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaActualizacionLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaUltimaConsultaGdeba")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaVencimiento")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FuenteUltimaRespuesta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TrataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UltimoErrorConsulta")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("FechaVencimiento");

                    b.HasIndex("TrataId")
                        .IsUnique();

                    b.ToTable("Cache_TrataControl", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataGdeba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcronimoGedo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("EsAutomatica")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsTrataManual")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdTrataGdeba")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoReservaDescripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoReservaDescripcionTipoReserva")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoReservaId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TratasGdeba", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataHabilitadaVialidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcronimoGedo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("CaratulaVariable")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoOrganismo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoReparticion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoTrata")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DescripcionTrata")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("EsAutomatica")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsTrataManual")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoTrata")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdTrataGdeba")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreOrganismo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NombreReparticion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool?>("PermisoCaratulacion")
                        .HasColumnType("bit");

                    b.Property<bool?>("PermisoReserva")
                        .HasColumnType("bit");

                    b.Property<bool?>("ReservaTotal")
                        .HasColumnType("bit");

                    b.Property<string>("TipoReservaDescripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoReservaDescripcionTipoReserva")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoReservaId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoOrganismo");

                    b.HasIndex("CodigoReparticion");

                    b.HasIndex("CodigoTrata");

                    b.HasIndex("IdTrataGdeba");

                    b.HasIndex("CodigoTrata", "CodigoOrganismo", "CodigoReparticion")
                        .IsUnique();

                    b.ToTable("TratasHabilitadasVialidad", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Worker.EjecucionWorker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Enriquecidos")
                        .HasColumnType("int");

                    b.Property<int?>("Errores")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FechaFinalizacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaInicio")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Origen")
                        .HasColumnType("int");

                    b.Property<int?>("Procesados")
                        .HasColumnType("int");

                    b.Property<int>("Proceso")
                        .HasColumnType("int");

                    b.Property<string>("Resumen")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("SinDatos")
                        .HasColumnType("int");

                    b.Property<Guid?>("SolicitudEjecucionWorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudEjecucionWorkerId")
                        .IsUnique()
                        .HasFilter("[SolicitudEjecucionWorkerId] IS NOT NULL");

                    b.HasIndex("Proceso", "FechaInicio");

                    b.ToTable("Worker_Ejecuciones", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Worker.EjecucionWorkerDescubrimientoTrataEstado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Actualizados")
                        .HasColumnType("int");

                    b.Property<int>("Creados")
                        .HasColumnType("int");

                    b.Property<int>("Descartados")
                        .HasColumnType("int");

                    b.Property<Guid>("EjecucionWorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstadoExpedienteGdebaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaResolucion")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Habilitados")
                        .HasColumnType("int");

                    b.Property<int>("RecibidosGdeba")
                        .HasColumnType("int");

                    b.Property<int>("SinCambios")
                        .HasColumnType("int");

                    b.Property<Guid>("TrataHabilitadaVialidadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EjecucionWorkerId");

                    b.HasIndex("EstadoExpedienteGdebaId");

                    b.HasIndex("TrataHabilitadaVialidadId");

                    b.HasIndex("EjecucionWorkerId", "TrataHabilitadaVialidadId", "EstadoExpedienteGdebaId")
                        .IsUnique();

                    b.ToTable("WorkerDescubrimiento_EjecucionesPorTrataEstado", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Worker.EjecucionWorkerExpedienteDescubierto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EjecucionWorkerDescubrimientoTrataEstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.HasIndex("EjecucionWorkerDescubrimientoTrataEstadoId", "ExpedienteId")
                        .IsUnique();

                    b.ToTable("WorkerDescubrimiento_ExpedientesDescubiertosPorEjecucionTrataEstado", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Worker.SolicitudEjecucionWorker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EjecucionWorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FechaFinalizacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaInicio")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaSolicitud")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Proceso")
                        .HasColumnType("int");

                    b.Property<string>("SolicitadaPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EjecucionWorkerId")
                        .IsUnique()
                        .HasFilter("[EjecucionWorkerId] IS NOT NULL");

                    b.HasIndex("Proceso", "Estado", "FechaSolicitud");

                    b.ToTable("Worker_SolicitudesEjecucion", (string)null);
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ArchivoAdjuntoExpediente", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", "Expediente")
                        .WithMany("ArchivosAdjuntos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Configuracion.ConfiguracionDescubrimientoEstadoExpediente", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.EstadoExpedienteGdeba", "EstadoExpedienteGdeba")
                        .WithMany()
                        .HasForeignKey("EstadoExpedienteGdebaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoExpedienteGdeba");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Configuracion.ConfiguracionDescubrimientoTemaExpediente", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TemaExpediente", "TemaExpediente")
                        .WithMany()
                        .HasForeignKey("TemaExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemaExpediente");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Configuracion.ConfiguracionEnriquecimientoMetadataDocumentoTemaExpediente", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TemaExpediente", "TemaExpediente")
                        .WithMany()
                        .HasForeignKey("TemaExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemaExpediente");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoArchivoLocal", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoGdeba", "Documento")
                        .WithOne("ArchivoLocal")
                        .HasForeignKey("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoArchivoLocal", "DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoCacheControl", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoGdeba", "Documento")
                        .WithOne("CacheControl")
                        .HasForeignKey("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoCacheControl", "DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoGdeba", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TipoDocumentoGdeba", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataHabilitadaVialidad", "Trata")
                        .WithMany("Expedientes")
                        .HasForeignKey("TrataId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Trata");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ExpedienteCacheControl", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", "Expediente")
                        .WithOne("CacheControl")
                        .HasForeignKey("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ExpedienteCacheControl", "ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ExpedienteDocumento", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoGdeba", "Documento")
                        .WithMany("Expedientes")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", "Expediente")
                        .WithMany("Documentos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.ExpedienteRelacion", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", "ExpedienteOrigen")
                        .WithMany("Relaciones")
                        .HasForeignKey("ExpedienteOrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", "ExpedienteRelacionado")
                        .WithMany()
                        .HasForeignKey("ExpedienteRelacionadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExpedienteOrigen");

                    b.Navigation("ExpedienteRelacionado");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.HistorialDocumentoGdeba", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoGdeba", "Documento")
                        .WithMany("Historial")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.HistorialExpedienteCacheControl", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", "Expediente")
                        .WithOne("HistorialCacheControl")
                        .HasForeignKey("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.HistorialExpedienteCacheControl", "ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.MovimientoExpediente", "UltimoMovimientoDetectado")
                        .WithMany()
                        .HasForeignKey("UltimoMovimientoDetectadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Expediente");

                    b.Navigation("UltimoMovimientoDetectado");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.InvocacionGdeba", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.OperacionGdeba", "Operacion")
                        .WithMany("Invocaciones")
                        .HasForeignKey("OperacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operacion");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.MovimientoExpediente", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", "Expediente")
                        .WithMany("Movimientos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.RegistroAuditoria", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.AplicacionConsumidora", "AplicacionConsumidora")
                        .WithMany("RegistrosAuditoria")
                        .HasForeignKey("AplicacionConsumidoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AplicacionConsumidora");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TemaExpedienteTrata", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TemaExpediente", "TemaExpediente")
                        .WithMany("Tratas")
                        .HasForeignKey("TemaExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataHabilitadaVialidad", "TrataHabilitadaVialidad")
                        .WithMany("TemasExpediente")
                        .HasForeignKey("TrataHabilitadaVialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemaExpediente");

                    b.Navigation("TrataHabilitadaVialidad");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataCacheControl", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataHabilitadaVialidad", "Trata")
                        .WithOne("CacheControl")
                        .HasForeignKey("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataCacheControl", "TrataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trata");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Worker.EjecucionWorkerDescubrimientoTrataEstado", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Worker.EjecucionWorker", "EjecucionWorker")
                        .WithMany("ResultadosDescubrimientoTrataEstado")
                        .HasForeignKey("EjecucionWorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.EstadoExpedienteGdeba", "EstadoExpedienteGdeba")
                        .WithMany()
                        .HasForeignKey("EstadoExpedienteGdebaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataHabilitadaVialidad", "TrataHabilitadaVialidad")
                        .WithMany()
                        .HasForeignKey("TrataHabilitadaVialidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EjecucionWorker");

                    b.Navigation("EstadoExpedienteGdeba");

                    b.Navigation("TrataHabilitadaVialidad");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Worker.EjecucionWorkerExpedienteDescubierto", b =>
                {
                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Worker.EjecucionWorkerDescubrimientoTrataEstado", "EjecucionWorkerDescubrimientoTrataEstado")
                        .WithMany("ExpedientesDescubiertos")
                        .HasForeignKey("EjecucionWorkerDescubrimientoTrataEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EjecucionWorkerDescubrimientoTrataEstado");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.AplicacionConsumidora", b =>
                {
                    b.Navigation("RegistrosAuditoria");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.DocumentoGdeba", b =>
                {
                    b.Navigation("ArchivoLocal");

                    b.Navigation("CacheControl");

                    b.Navigation("Expedientes");

                    b.Navigation("Historial");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Expediente", b =>
                {
                    b.Navigation("ArchivosAdjuntos");

                    b.Navigation("CacheControl");

                    b.Navigation("Documentos");

                    b.Navigation("HistorialCacheControl");

                    b.Navigation("Movimientos");

                    b.Navigation("Relaciones");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.OperacionGdeba", b =>
                {
                    b.Navigation("Invocaciones");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TemaExpediente", b =>
                {
                    b.Navigation("Tratas");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.TrataHabilitadaVialidad", b =>
                {
                    b.Navigation("CacheControl");

                    b.Navigation("Expedientes");

                    b.Navigation("TemasExpediente");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Worker.EjecucionWorker", b =>
                {
                    b.Navigation("ResultadosDescubrimientoTrataEstado");
                });

            modelBuilder.Entity("ServicioSistemaWebProxyGdebaDvba.Domain.Entities.Worker.EjecucionWorkerDescubrimientoTrataEstado", b =>
                {
                    b.Navigation("ExpedientesDescubiertos");
                });
#pragma warning restore 612, 618
        }
    }
}
