using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ServicioSistemaWebProxyGdebaDvba.Infrastructure.Persistence;

#nullable disable

namespace ServicioSistemaWebProxyGdebaDvba.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProxyGdebaDbContext))]
    [Migration("20260623183147_CargaTratasHabilitadasVialidad")]
    public partial class CargaTratasHabilitadasVialidad : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"MERGE dbo.TratasHabilitadasVialidad AS target
USING
(
    SELECT
        source.CodigoTrata,
        source.DescripcionTrata,
        source.EstadoTrata,
        source.ReservaTotal,
        source.CaratulaVariable,
        source.CodigoReparticion,
        source.NombreReparticion,
        source.CodigoOrganismo,
        source.NombreOrganismo,
        source.PermisoCaratulacion,
        source.PermisoReserva,
        trata.Id AS TrataId
    FROM (VALUES
        (N'AMB0019', N'Documentación Ambiental', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'AUT0012', N'Autorización a terceros para realizar trabajos en zona de camino', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'AUT0013', N'Autorización de accesos a propiedad privada y estaciones de servicio', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'AUT0014', N'Permisos de Siembra en Zona de Camino', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'AUT0016', N'Autorización de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'AUT0017', N'Autorización de instalaciones', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CERT0024', N'Presentación Digital Certificado de Obra - Vialidad', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'GADV', N'Gerencia de Administración', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CERT0024', N'Presentación Digital Certificado de Obra - Vialidad', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CERT0025', N'Reajuste de Certificado Provisorio 13-06 - Vialidad', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CERT0025', N'Reajuste de Certificado Provisorio 13-06 - Vialidad', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'GADV', N'Gerencia de Administración', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0002', N'Licitación Pública', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0003', N'Licitación de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0006', N'Gastos por Artículo 40 Ley 10.189', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0007', N'Licitación Privada', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0009', N'Prórroga de Orden de Compra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0010', N'Compras Ley 14815', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0011', N'Ampliación de Orden de Compra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0012', N'Redeterminación de Precios', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0013', N'Compra por Convenio Marco', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0014', N'Proyecto de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0015', N'Acta de Constatación', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'SGCVDV', N'Subgerencia de Concesiones Viales', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0017', N'Devolución de Póliza de Seguro', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0018', N'Revisión de Precios', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0019', N'Acta de Replanteo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0020', N'Acta de Medición Final de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0022', N'Orden de Compra Abierta', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0023', N'Remate Público', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0025', N'Convenio Marco de Compras', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0027', N'Neutralización de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0028', N'Rescisión de Contrato de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0029', N'Póliza de Fondo de Reparo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0030', N'Póliza de Anticipo Financiero', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0031', N'Certificado de Pago de Convenio con Municipio', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0032', N'Certificado de Pago de Convenio con Universidades', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0033', N'Trabajos Adicionales de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0034', N'Contratación de Trabajos Adicionales', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0035', N'Solicitud de Reclamo de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0036', N'Aprobación de Plan de Trabajo y Cronograma de Inversiones', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0037', N'Pago de Diferencias por Redeterminación de Precios', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0038', N'Aprobación de Estudio de Impacto Ambiental', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0039', N'Aprobación de la Traza y Declaratoria de Utilidad Pública', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0040', N'Pago de Anticipo Financiero', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0041', N'Transferencia de Reservas', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0042', N'Modificación de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0043', N'Actualización de Plan de Trabajo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0044', N'Reserva Mensual Por Lluvias y Consecuencias de Lluvia', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0045', N'Aplicación de Multa por Incumplimiento de Orden de Servicio', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0046', N'Reconocimiento Gastos Improductivos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0047', N'Presentación de Documentación Gráfica de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0049', N'Iniciativa de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0051', N'Elaboración de Proyectos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0052', N'Seguimiento de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0053', N'Certificación de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0055', N'Carpeta de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0059', N'Concurso de Precios', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0063', N'Adecuación Provisoria', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0069', N'Listado Personal a Afectar a la Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0070', N'Presentación Fórmula de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0071', N'Acta reinicio de obras', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0072', N'Mantenimiento rutinario de puentes', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0073', N'Equipamiento de Gabinete', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0074', N'Plan de trabajo y curva de inversión', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0075', N'Recepción Provisoria Parcial', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0076', N'Recepción Provisoria Total', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0077', N'Recepción Parcial de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0078', N'Planos Conforme a Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0081', N'Recepción definitiva de obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0082', N'Reserva de Días Perdidos por Art. 37 - Ley de Obras Públicas', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0083', N'Acta de Medición', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0087', N'Licitación Púbica Internacional', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'GADV', N'Gerencia de Administración', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(1 AS bit)),
        (N'COMP0087', N'Licitación Púbica Internacional', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0093', N'Medición Final Parcial y Recepción Provisoria', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0098', N'Redeterminaciones Provisorias', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'COMP0100', N'Pago de órdenes de compras de los distintos Convenios Marco', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CONT0002', N'Contrato de Locación de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CONT0003', N'Contrato de Locación de Servicios', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CONT0004', N'Rescisión de Contrato', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CONT0005', N'Adenda', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CONT0006', N'Convenio con Universidades', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CONT0007', N'Procedimiento Abreviado', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CONT0008', N'Factura Conformada', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CONT0009', N'Contratación Menor', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CONT0010', N'Contratación Directa por Excepción', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CONT0012', N'Contrato Locación de Inmueble', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CONT0020', N'Modificaciones del Contrato Vigente', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'CONT0021', N'Solicitud de Cumplimiento del Contrato de Concesión', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0000', N'Pago certificado de obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0002', N'Pago a Proveedores', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0007', N'Adecuación Presupuestaria', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0011', N'Pago de intereses', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0013', N'Pago COPRES (solicitud de combustible)', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0014', N'Pedido de fondos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0016', N'Liquidación de Orden de Pago Presupuestaria', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0017', N'Liquidación de Orden de Pago Extrapresupuestaria', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0018', N'Pedido de Fondos  para Pago de Bonificaciones', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(0 AS bit), CAST(0 AS bit)),
        (N'FIN0019', N'Pago de servicio', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0020', N'Reconocimiento de Gastos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0021', N'Constitución de Fondo Rotativo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0022', N'Alcance de pago', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0025', N'Reconocimiento de Crédito', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0028', N'Constitución de Caja Chica', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0029', N'Rendición de caja chica', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0030', N'Apertura de Caja Chica', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0031', N'Anticipo de Caja Chica', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0032', N'Programación del Gasto por Trimestre', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0033', N'Pedido de Fondos para Pago de Horas Extras', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0036', N'Transferencia de Crédito', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0038', N'Regularización Contable', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0040', N'Solicitud de Bonificaciones', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0041', N'Recursos Administrativos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0042', N'Pago de Subsidios', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0043', N'Pedido de Fondos Extrapresupuestarios', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0044', N'Auspicios', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0046', N'Pago de Retenciones', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0047', N'Pago POLAD', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0057', N'Elevación de Consultas', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0073', N'Rendición de Cuentas Mensual', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0121', N'Devolución a 229/07', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0124', N'Cierre de Ejercicio', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0147', N'Liquidación de Prestación Dineraria - Régimen de Autoseguro', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0148', N'Pago de Comisiones Bancarias', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0157', N'Haberes Pendientes de Pago', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0163', N'Cierre de Cuenta Bancaria', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0197', N'Aumento de Tarifa', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0221', N'Compensación de Gastos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0221', N'Compensación de Gastos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DPTLYGDV', N'Departamento Liquidación y Gastos', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0252', N'Reajuste de Certificados por Redeterminación de Precios', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0253', N'Reajuste por Adecuación Provisoria', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0312', N'Devolución a 63.735/8', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0322', N'Solicitud de pago de anticipo financiero - Vialidad', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'GADV', N'Gerencia de Administración', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'FIN0322', N'Solicitud de pago de anticipo financiero - Vialidad', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'INF0007', N'Procedimiento Sancionatorio', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'SGCVDV', N'Subgerencia de Concesiones Viales', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0001', N'Solicitud de Desarchivo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0003', N'Oficio Daños y Perjuicios', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0004', N'Solicitud de Subsidios', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0005', N'Ampliación de Plazo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0007', N'Proyecto de Decreto', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0011', N'Carta Documento', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0012', N'Reclamo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0013', N'Convenios', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0014', N'Proyecto de Disposición', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0018', N'Proyecto de Resolución', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0019', N'Proyecto de Ley', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0020', N'Delegación de Competencias', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0021', N'Adecuación de Estructura', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0022', N'Rectificación de Acto Administrativo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0023', N'Impugnación', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0024', N'Modificación de Acto Administrativo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0026', N'Proyecto de Acto Administrativo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0027', N'Autorización de Manejo de Vehículos Oficiales', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0029', N'Pronto Despacho', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0033', N'Modificación de Plazo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0075', N'Inspectores Zonales-Kilometraje', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'SGCVDV', N'Subgerencia de Concesiones Viales', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0076', N'Solicitud de Informes', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'SGCVDV', N'Subgerencia de Concesiones Viales', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0087', N'Solicitud de Verificación Técnica Vehicular', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0093', N'Accidentes de vehículos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0094', N'Donación Vehículos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0098', N'Reconstrucción de Expedientes', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0104', N'Actas', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0113', N'Embargo Judicial', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0118', N'Bonificaciones Informáticas', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0124', N'Siniestro Automotor', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0208', N'Transferencia de Movilidad', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0254', N'Expropiaciones', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0313', N'Croquis del Obrador', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0314', N'Elevación Ensayos de Laboratorio', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0319', N'Orden de Servicio', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0347', N'Comprobantes Conservación', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0349', N'Atención y Firma del Despacho', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0351', N'Intereses sobre Pago de Haberes Pendientes', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0355', N'Acta Habilitación al Tránsito', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0357', N'Informes Mensuales de Gestión', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0360', N'Reclamo por Mora', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0369', N'Ingreso de Postulantes ( Curriculum)', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0370', N'Corrección de Errores Formales en Actos Administrativos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0373', N'Solicitud de Eliminación de Expedientes', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0445', N'Reasignación de Expediente Papel', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0448', N'Transferencia de Equipo Auxiliar', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0449', N'Requerimiento AFIP/ARBA', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0452', N'Comparativa por Reajuste Final de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0462', N'Pruebas de Carga de Puente', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0465', N'Toma de Vista', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0561', N'Notificación de disposición de designación de cuerpo de inspección', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0575', N'Adhesión al decreto 290/2021', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0594', N'Gestiones de tecnologías móviles', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'SGACDV', N'Subgerencia Administrativo Contable', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0713', N'Presentación Digital - Trámite General Vialidad', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'GADV', N'Gerencia de Administración', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0713', N'Presentación Digital - Trámite General Vialidad', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0719', N'Prueba de Suficiencia - art. 35 Ley N° 10.328', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0738', N'Permiso para vincular Propiedades Privadas con Rutas Provinciales', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0739', N'Visado de Planos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0740', N'Permisos de Tendidos y Cruces de Servicios en Zona de Camino', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'OTR0741', N'Permisos de Trabajos y Obras de Terceros en Zona de Camino', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PAT0001', N'Patrimonio - Altas', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PAT0002', N'Patrimonio - Bajas', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PAT0004', N'Patrimonio - Transferencias', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PAT0005', N'Patrimonio - Recuentos físicos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PAT0006', N'Actualización del Inventario General de Bienes', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0003', N'Cese por fallecimiento', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0005', N'Reconocimiento de Días por Licencia Médica', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0006', N'Cambio de Agrupamiento', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0009', N'Devolución de Importe', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0011', N'Asignacion Familiar', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(0 AS bit), CAST(0 AS bit)),
        (N'PER0013', N'Cese por Renuncia A Planta Permanente', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0016', N'Proceso Calificatorio', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0019', N'Reserva de Cargo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0021', N'Designación de Personal de Gabinete', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0023', N'Designación en Planta Permanente', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0025', N'Reconocimiento de Servicios', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0027', N'Cese por abandono de cargo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0028', N'Licencia Decenal', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0030', N'Licencia por Actividad Politica', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0031', N'Licencia por Actividad Gremial', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0033', N'Pase a planta permanente', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0035', N'Designacion de Secretario Privado', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0037', N'Licencia de estudios o perfeccionamiento (art. 115 inc. a)', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0038', N'Renuncia A Planta Temporaria', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0039', N'Licencia sin goce de haberes', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0041', N'Designación de Personal Jerárquico', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0045', N'Junta Médica', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0049', N'Limitación Reserva de Cargo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0051', N'Jubilación Ejecutiva', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0052', N'Jubilación por Incapacidad', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0059', N'Limitación de Funciones', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0060', N'Designación de Personal Contratado', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0061', N'Limitación de Comisión', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0062', N'Modificación de asignación de módulos del Personal de Gabinete', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0073', N'Permiso por Estudios y Actividades Culturales', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0074', N'Permiso por Actividades Deportivas', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0077', N'Designación en Planta Permanente sin Estabilidad', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0078', N'Descuento por Licencias Injustificadas', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0082', N'Recurso de Revocatoria', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0084', N'Liquidación de Licencia Anual no Gozada', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0085', N'Designación de Personal Transitorio', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0086', N'Recategorizaciones', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0088', N'Aprobación de Planteles Básicos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0093', N'Ubicación del Personal - art 171 de la Ley 10430', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0094', N'Vacancia Temporal', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0095', N'Designación de Personal con Discapacidad (Ley Nro. 10.592)', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0096', N'Confección de Liquidación Final ante Cese de Personal', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0097', N'Designación de Responsables Patrimoniales', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0098', N'Incorporación Ley 10.592', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0099', N'Confección de los Planteles Básicos del Personal', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0100', N'Modificación de los Planteles Básicos del Personal', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0108', N'Cese por Renuncia de Funcionario', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0112', N'Solicitud de Junta Médica', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0127', N'Limitacion de Licencia', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0131', N'Reconocimiento de Funciones', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0132', N'Comisión de Servicios', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0145', N'Suspensión Preventiva', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0148', N'Cambio De Régimen Horario', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0151', N'Reubicaciones', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0152', N'Renuncia al Cargo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0165', N'Cese por Jubilación', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0184', N'Nomenclador de Cargos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0202', N'Designación de Representantes', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0205', N'Concursos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0230', N'Asignación de Funciones', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0244', N'Designación en Planta Temporaria Ley 14783', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0253', N'Permisos Art. 61 (Ley 10.430)', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0263', N'Concurso para cobertura de cargo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0274', N'Bonificación de Títulos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0305', N'Designación Jefe de Inspección', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0306', N'Designación Representante de Obra', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0307', N'Listado de Nómina de Equipos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0310', N'Permiso Especial con o sin Goce de Haberes', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0313', N'Artículo 87 - Ley 10430', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0315', N'Ascenso de Categoría', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0318', N'Nómina de personal y ART', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0320', N'Rectificación Datos Personales', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0324', N'Compatibilidad/Incompatibilidad de cargos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0345', N'Traslado Definitivo con/sin Cargo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0392', N'Licencia para Mujeres Víctimas de Violencia', N'ALTA', CAST(1 AS bit), CAST(NULL AS bit), N'SGRRHHDV', N'Subgerencia de Recursos Humanos', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0397', N'Postulación de profesionales en psicología en el marco del Decreto 24/2024', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'SGRRHHDV', N'Subgerencia de Recursos Humanos', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PER0398', N'Proceso de selección de personal en el marco del Decreto 24/2024', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'SGRRHHDV', N'Subgerencia de Recursos Humanos', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'PROD0003', N'Evaluación de Impacto Ambiental', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'RES0019', N'Tramitaciones Ley N° 14.783', N'ALTA', CAST(1 AS bit), CAST(NULL AS bit), N'SGRRHHDV', N'Subgerencia de Recursos Humanos', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'RES0027', N'Sumarios Ley N° 14.893-Decreto N° 121/2020', N'ALTA', CAST(1 AS bit), CAST(NULL AS bit), N'SGRRHHDV', N'Subgerencia de Recursos Humanos', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'SLYT0005', N'Pedido de Informe', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'SGCVDV', N'Subgerencia de Concesiones Viales', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'SLYT0006', N'Oficios Judiciales', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'SOL0031', N'Solicitud de Informes', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'SOL0092', N'Solicitud de información pública Vialidad', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'SOL0094', N'Solicitud Medición final y recepción provisoria - recepción definitiva', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'SUM0001', N'Sumario Administrativo', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'SUM0002', N'Investigación Pre-Sumarial', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'SUM0005', N'Sumario Administrativo reservado', N'ALTA', CAST(1 AS bit), CAST(NULL AS bit), N'SGRRHHDV', N'Subgerencia de Recursos Humanos', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit)),
        (N'VIATI0004', N'Pedido de Fondos para Pago de Viaticos', N'ALTA', CAST(0 AS bit), CAST(NULL AS bit), N'DVMIYSPGP', N'Dirección de Vialidad', N'DVMIYSPGP', N'Dirección de Vialidad', CAST(1 AS bit), CAST(0 AS bit))
    ) AS source
    (
        CodigoTrata,
        DescripcionTrata,
        EstadoTrata,
        ReservaTotal,
        CaratulaVariable,
        CodigoReparticion,
        NombreReparticion,
        CodigoOrganismo,
        NombreOrganismo,
        PermisoCaratulacion,
        PermisoReserva
    )
    LEFT JOIN dbo.TratasGdeba AS trata ON trata.Codigo = source.CodigoTrata
) AS source
ON target.CodigoTrata = source.CodigoTrata
    AND target.CodigoOrganismo = source.CodigoOrganismo
    AND target.CodigoReparticion = source.CodigoReparticion
WHEN MATCHED THEN
    UPDATE SET
        target.TrataId = source.TrataId,
        target.DescripcionTrata = source.DescripcionTrata,
        target.EstadoTrata = source.EstadoTrata,
        target.ReservaTotal = source.ReservaTotal,
        target.CaratulaVariable = source.CaratulaVariable,
        target.NombreReparticion = source.NombreReparticion,
        target.NombreOrganismo = source.NombreOrganismo,
        target.PermisoCaratulacion = source.PermisoCaratulacion,
        target.PermisoReserva = source.PermisoReserva
WHEN NOT MATCHED BY TARGET THEN
    INSERT
    (
        Id,
        TrataId,
        CodigoTrata,
        DescripcionTrata,
        EstadoTrata,
        ReservaTotal,
        CaratulaVariable,
        CodigoReparticion,
        NombreReparticion,
        CodigoOrganismo,
        NombreOrganismo,
        PermisoCaratulacion,
        PermisoReserva
    )
    VALUES
    (
        NEWID(),
        source.TrataId,
        source.CodigoTrata,
        source.DescripcionTrata,
        source.EstadoTrata,
        source.ReservaTotal,
        source.CaratulaVariable,
        source.CodigoReparticion,
        source.NombreReparticion,
        source.CodigoOrganismo,
        source.NombreOrganismo,
        source.PermisoCaratulacion,
        source.PermisoReserva
    );
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DELETE target
FROM dbo.TratasHabilitadasVialidad AS target
WHERE target.CodigoOrganismo = N'DVMIYSPGP';
");
        }
    }
}
