using ServicioSistemaWebProxyGdebaDvba.Domain.Enums;

namespace ServicioSistemaWebProxyGdebaDvba.Application.Expedientes.Models;

public sealed record DescubrirExpedientesProgramadosRequest(int MaximoInvocaciones, int ConsultasVaciasParaPausa, int DiasPausaSinResultados, OrigenInvocacionGdeba OrigenInvocacion);
